#!/usr/bin/env pypy3
# -*- coding: utf-8 -*-
"""
GAW — Stacked Labour-Block Economy / Gestapelte Arbeitsblock-Wirtschaft
Very colorful PyPy3-compatible terminal simulation with UTF-8 art.

Run examples:
    pypy3 gaw_pypy3_utf8_art_simulation.py
    pypy3 gaw_pypy3_utf8_art_simulation.py --lang de
    pypy3 gaw_pypy3_utf8_art_simulation.py --scenario crisis --periods 8 --seed 7
    pypy3 gaw_pypy3_utf8_art_simulation.py --parts factors,work,market,final
    pypy3 gaw_pypy3_utf8_art_simulation.py --no-color

No external packages are required. The UTF-8 art is printed directly into the
program output. No separate art file is generated by the program.
"""

from __future__ import annotations

import argparse
import os
import random
import re
import shutil
import sys
import textwrap
from dataclasses import dataclass, field
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Tuple

ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


# =============================================================================
#  Terminal UI: colors, unit badges, tables, UTF-8 art
# =============================================================================

class UI:
    """ANSI-256 terminal UI. Designed to work under PyPy3 with stdlib only."""

    UNIT_STYLE: Dict[str, Tuple[int, int]] = {
        # unit: (foreground, background)
        "ID": (16, 244),
        "E": (16, 45),
        "3D": (16, 213),
        "O": (16, 82),
        "O+": (16, 118),
        "O-": (231, 196),
        "M": (16, 201),
        "Mwir": (16, 207),
        "K": (231, 33),
        "Q": (231, 129),
        "AW": (16, 220),
        "P": (16, 208),
        "S": (231, 197),
        "ST": (16, 141),
        "α": (16, 39),
        "β": (16, 77),
        "γ": (16, 162),
        "GF": (16, 51),
        "GM": (16, 226),
        "T": (16, 117),
        "R": (16, 166),
        "KR": (16, 214),
        "B": (16, 34),
        "REG": (16, 40),
        "ENT": (16, 202),
        "SCH": (231, 160),
    }

    UNIT_FG: Dict[str, int] = {
        "ID": 250, "E": 45, "3D": 213, "O": 82, "O+": 118, "O-": 196,
        "M": 201, "Mwir": 207, "K": 33, "Q": 129, "AW": 220, "P": 208,
        "S": 197, "ST": 141, "α": 39, "β": 77, "γ": 162,
        "GF": 51, "GM": 226, "T": 117, "R": 166, "KR": 214,
        "B": 34, "REG": 40, "ENT": 202, "SCH": 160,
    }

    RAINBOW = [196, 202, 226, 46, 51, 39, 129, 201, 213, 118]
    FIRE = [196, 202, 208, 214, 220, 226]
    WATER = [20, 27, 33, 39, 45, 51, 87]
    FOREST = [22, 28, 34, 40, 46, 82, 118]
    VIOLET = [54, 91, 93, 129, 165, 201, 207]

    def __init__(self, color: bool = True, width: Optional[int] = None) -> None:
        self.color = bool(color)
        if width is None:
            width = shutil.get_terminal_size((116, 32)).columns
        self.width = max(82, min(150, int(width)))

    def c(self, text: object, fg: Optional[int] = None, bg: Optional[int] = None,
          bold: bool = False, dim: bool = False) -> str:
        text = str(text)
        if not self.color:
            return text
        codes: List[str] = []
        if bold:
            codes.append("1")
        if dim:
            codes.append("2")
        if fg is not None:
            codes.append("38;5;%d" % fg)
        if bg is not None:
            codes.append("48;5;%d" % bg)
        if not codes:
            return text
        return "\033[%sm%s\033[0m" % (";".join(codes), text)

    def strip(self, text: object) -> str:
        return ANSI_RE.sub("", str(text))

    def unit(self, name: str) -> str:
        fg, bg = self.UNIT_STYLE.get(name, (231, 238))
        return self.c(" %s " % name, fg=fg, bg=bg, bold=True)

    def amount(self, value: float, unit: str, digits: int = 2, signed: bool = False) -> str:
        sign = "+" if signed else ""
        spec = sign + ",." + str(digits) + "f"
        number = format(float(value), spec).replace(",", "_")
        return self.c(number, fg=self.UNIT_FG.get(unit, 231), bold=True) + " " + self.unit(unit)

    def rawnum(self, value: float, digits: int = 2, signed: bool = False) -> str:
        sign = "+" if signed else ""
        spec = sign + ",." + str(digits) + "f"
        return format(float(value), spec).replace(",", "_")

    def rainbow(self, text: str, palette: Optional[Sequence[int]] = None, bold: bool = True) -> str:
        if not self.color:
            return text
        colors = list(palette or self.RAINBOW)
        out: List[str] = []
        idx = 0
        for ch in text:
            if ch.isspace():
                out.append(ch)
            else:
                out.append(self.c(ch, fg=colors[idx % len(colors)], bold=bold))
                idx += 1
        return "".join(out)

    def rule(self, char: str = "═", palette: Optional[Sequence[int]] = None) -> None:
        print(self.rainbow(char * self.width, palette=palette or self.RAINBOW))

    def title(self, text: str, bg: int = 220, fg: int = 16) -> None:
        print()
        self.rule("═", self.RAINBOW)
        inner = "  " + text.strip() + "  "
        pad = max(0, self.width - len(inner))
        left = pad // 2
        right = pad - left
        print(self.c(" " * left + inner + " " * right, fg=fg, bg=bg, bold=True))
        self.rule("═", self.RAINBOW)

    def sub(self, text: str, bg: int = 54, fg: int = 231) -> None:
        print(self.c("  " + text + "  ", fg=fg, bg=bg, bold=True))

    def wrap(self, text: str, indent: int = 0) -> None:
        width = max(52, self.width - indent)
        prefix = " " * indent
        for para in text.strip().split("\n"):
            if not para.strip():
                print()
                continue
            print(textwrap.fill(para.strip(), width=width,
                                initial_indent=prefix, subsequent_indent=prefix))

    def kv(self, key: str, value: str) -> None:
        print("  " + self.c(key, fg=229, bold=True) + self.c(" → ", fg=244) + value)

    def bullet(self, text: str, color: int = 220, indent: int = 2) -> None:
        marker = self.c("◆", fg=color, bold=True)
        wrapped = textwrap.wrap(text.strip(), width=max(52, self.width - indent - 4)) or [""]
        print(" " * indent + marker + " " + wrapped[0])
        for line in wrapped[1:]:
            print(" " * (indent + 2) + line)

    def heat(self, value: float, low: float = 0.85, high: float = 2.2, lang: str = "en") -> str:
        labels = {
            "en": ("low", "normal", "high", "critical"),
            "de": ("niedrig", "normal", "hoch", "kritisch"),
        }[lang]
        if value < low:
            return self.c(" %s " % labels[0], fg=16, bg=82, bold=True)
        if value < 1.20:
            return self.c(" %s " % labels[1], fg=16, bg=46, bold=True)
        if value < high:
            return self.c(" %s " % labels[2], fg=16, bg=208, bold=True)
        return self.c(" %s " % labels[3], fg=231, bg=196, bold=True)

    def print_art(self, lines: Sequence[str], palette: Optional[Sequence[int]] = None) -> None:
        palette = palette or self.RAINBOW
        for line in lines:
            print("  " + self.rainbow(line.rstrip(), palette=palette))

    def table(self, headers: Sequence[str], rows: Sequence[Sequence[object]],
              right: Optional[Iterable[int]] = None) -> None:
        right_set = set(right or [])
        data = [[str(cell) for cell in row] for row in rows]
        heads = [self.c(h, fg=16, bg=250, bold=True) for h in headers]
        all_rows = [heads] + data
        widths: List[int] = []
        for col in range(len(headers)):
            width = max(len(self.strip(row[col])) for row in all_rows)
            widths.append(min(max(width, 3), 42))

        def fit(cell: str, width: int) -> str:
            raw = self.strip(cell)
            if len(raw) <= width:
                return cell
            return raw[:max(1, width - 1)] + "…"

        def line(row: Sequence[str], is_header: bool = False) -> str:
            parts: List[str] = []
            for i, cell in enumerate(row):
                cell = fit(cell, widths[i])
                raw_len = len(self.strip(cell))
                pad = widths[i] - raw_len
                if i in right_set and not is_header:
                    parts.append(" " * pad + cell)
                else:
                    parts.append(cell + " " * pad)
            return "  " + self.c("│", fg=245) + (" " + self.c("│", fg=245) + " ").join(parts) + self.c("│", fg=245)

        top = "  " + self.c("┌" + "┬".join("─" * (w + 2) for w in widths) + "┐", fg=245)
        mid = "  " + self.c("├" + "┼".join("─" * (w + 2) for w in widths) + "┤", fg=245)
        bot = "  " + self.c("└" + "┴".join("─" * (w + 2) for w in widths) + "┘", fg=245)
        print(top)
        print(line(heads, True))
        print(mid)
        for row in data:
            print(line(row))
        print(bot)


# =============================================================================
#  Localized labels and unit explanations
# =============================================================================

WORDS = {
    "en": {
        "program_title": "GAW — STACKED LABOUR-BLOCK ECONOMY",
        "subtitle": "very colorful UTF-8 simulation of a work-backed currency",
        "scenario": "Scenario",
        "periods": "Periods",
        "seed": "Seed",
        "language": "Language",
        "what_why": "What is simulated, and why?",
        "units_here": "Units and abbreviations in this UTF-8 scene only",
        "art": "UTF-8 simulation art",
        "calculation": "Calculation and simulated values",
        "summary": "Summary and evaluation below this UTF-8 scene",
        "possible": "Different outcomes this part could produce",
        "formula": "Formula",
        "result": "Result",
        "end": "END OF SIMULATION",
        "start": "start",
        "income": "income",
        "expense": "expense",
        "control": "control",
        "sold": "sold",
        "loss": "warehouse loss",
        "accepted": "accepted",
        "reduced": "reduced",
        "rejected": "rejected",
        "scenario_normal": "normal",
        "scenario_crisis": "crisis",
        "scenario_research": "research",
        "scenario_housebuilding": "housebuilding",
    },
    "de": {
        "program_title": "GAW — GESTAPELTE ARBEITSBLOCK-WIRTSCHAFT",
        "subtitle": "sehr bunte UTF-8-Simulation einer arbeitsgedeckten Währung",
        "scenario": "Szenario",
        "periods": "Perioden",
        "seed": "Seed",
        "language": "Sprache",
        "what_why": "Was wird simuliert, und warum?",
        "units_here": "Einheiten und Kürzel nur in dieser UTF-8-Szene",
        "art": "UTF-8-Simulationskunst",
        "calculation": "Berechnung und simulierte Werte",
        "summary": "Zusammenfassung und Auswertung unter dieser UTF-8-Szene",
        "possible": "Verschiedene Ausgänge, die dieser Teil erzeugen könnte",
        "formula": "Formel",
        "result": "Ergebnis",
        "end": "ENDE DER SIMULATION",
        "start": "Start",
        "income": "Einnahme",
        "expense": "Ausgabe",
        "control": "Steuerung",
        "sold": "verkauft",
        "loss": "Lagerverlust",
        "accepted": "bestätigt",
        "reduced": "gekürzt",
        "rejected": "abgelehnt",
        "scenario_normal": "normal",
        "scenario_crisis": "Krise",
        "scenario_research": "Forschung",
        "scenario_housebuilding": "Hausbau",
    },
}


def L(lang: str, key: str) -> str:
    return WORDS[lang][key]


UNIT_INFO: Dict[str, Dict[str, str]] = {
    "ID": {
        "en": "Identifier. ID names a work block, segment, test case, or ledger entry so the simulation can trace which item was produced, checked, stacked, sold, reduced, or rejected. It is not economic value by itself; it is the address of the value claim.",
        "de": "Kennnummer. ID benennt einen Arbeitsblock, ein Segment, einen Prüffall oder einen Registereintrag, damit die Simulation verfolgen kann, welcher Eintrag erzeugt, geprüft, gestapelt, verkauft, gekürzt oder abgelehnt wurde. Sie ist selbst kein Wert, sondern die Adresse des Wertanspruchs.",
    },
    "E": {
        "en": "Input units. E counts what enters the work: material, energy, time, information, tools, soil preparation, or previous labour used by the process. Inputs matter because a price must know what was consumed before output existed.",
        "de": "Eingangseinheiten. E zählt, was in die Arbeit hineingeht: Material, Energie, Zeit, Information, Werkzeuge, Bodenvorbereitung oder Vorarbeit. Eingänge sind wichtig, weil ein Preis wissen muss, was verbraucht wurde, bevor Output entsteht.",
    },
    "3D": {
        "en": "Three-dimensional work. 3D is not a formula variable here; it marks work on volume, bodies, buildings, machines, pipes, bridges, storage shells, and spatial structures. In the factor scale it is used as the short visible name for housebuilding-type labour.",
        "de": "Dreidimensionale Arbeit. 3D ist hier keine Formelvariable, sondern markiert Arbeit an Volumen, Körpern, Gebäuden, Maschinen, Leitungen, Brücken, Lagerräumen und räumlichen Strukturen. In der Faktorenskala steht es als kurzer sichtbarer Name für Häuserbau-Arbeit.",
    },
    "O": {
        "en": "Output units. O counts useful results after the work: goods, repaired states, services, information, better coordination, or a finished part. In price calculation output is weighted more strongly than input because it is the usable result.",
        "de": "Ausgangseinheiten. O zählt die nützlichen Ergebnisse nach der Arbeit: Güter, reparierte Zustände, Dienstleistungen, Informationen, bessere Koordination oder fertige Teile. In der Preisrechnung wird Output stärker gewichtet als Input, weil er das nutzbare Ergebnis ist.",
    },
    "O+": {
        "en": "Positive output. O+ counts only beneficial effects: a working product, a corrected plan, recovered capacity, solved confusion, or repaired damage. It separates useful consequence from mere activity.",
        "de": "Positiver Ausgang. O+ zählt nur nützliche Wirkungen: ein funktionierendes Produkt, einen korrigierten Plan, zurückgewonnene Kapazität, gelöste Verwirrung oder reparierten Schaden. Es trennt nützliche Folge von bloßer Aktivität.",
    },
    "O-": {
        "en": "Negative output. O- counts harmful effects: wrong mathematics, pollution, failed coordination, broken material, misinformation, or newly created risk. It is not ignored; it is subtracted with a damage weight.",
        "de": "Negativer Ausgang. O- zählt schädliche Wirkungen: falsche Mathematik, Verschmutzung, misslungene Koordination, zerstörtes Material, Fehlinformation oder neu erzeugtes Risiko. Er wird nicht ignoriert, sondern mit einem Schadensgewicht abgezogen.",
    },
    "M": {
        "en": "Work amount. M is the raw amount of labour movement in the basic model, usually E + O or an equivalent segment amount. M does not yet say whether the work is important; it only says how large the measured work block is.",
        "de": "Arbeitsmenge. M ist im Grundmodell die rohe Menge der Arbeitsbewegung, meist E + O oder eine gleichwertige Segmentmenge. M sagt noch nicht, ob die Arbeit wichtig ist; es sagt nur, wie groß der gemessene Arbeitsblock ist.",
    },
    "Mwir": {
        "en": "Effective work amount. Mwir is the amount left after negative output has been subtracted with γ. It can become negative, which means that the work caused more damage than useful transformation.",
        "de": "Wirksame Arbeitsmenge. Mwir ist die Menge, die übrig bleibt, nachdem negativer Ausgang mit γ abgezogen wurde. Sie kann negativ werden; dann hat die Arbeit mehr Schaden als nützliche Transformation erzeugt.",
    },
    "K": {
        "en": "Work factor. K is the multiplier for the type and leverage of work: agriculture starts at 1, area work at 2, 3D work at 3, time-critical work at 4, causally important work at 5, mental work at 6, communication at 7, block decomposition at 8, and mathematics at 10. Combined properties use the additive stacking rule so values do not explode.",
        "de": "Arbeitsfaktor. K ist der Multiplikator für Arbeitsart und Hebelwirkung: Ackerarbeit startet bei 1, Flächenarbeit bei 2, 3D-Arbeit bei 3, zeitkritische Arbeit bei 4, kausal wichtige Arbeit bei 5, geistige Arbeit bei 6, Kommunikation bei 7, Blockzerlegung bei 8 und Mathematik bei 10. Kombinierte Eigenschaften nutzen die additive Stapelregel, damit Werte nicht explodieren.",
    },
    "Q": {
        "en": "Quality factor. Q is the verified quality of the work. Q = 1.00 means standard quality, lower values reduce the claim, values above 1 reward superior output, and Q = 0 can erase a claim even if effort was high.",
        "de": "Qualitätsfaktor. Q ist die geprüfte Güte der Arbeit. Q = 1,00 bedeutet Standardqualität, niedrigere Werte kürzen den Anspruch, Werte über 1 belohnen besseren Output, und Q = 0 kann den Anspruch löschen, obwohl Aufwand vorhanden war.",
    },
    "AW": {
        "en": "Labour currency. AW is the credited value of verified useful work. It can be paid, stacked into a product, taxed, issued by a public fund, destroyed through repayment, or become debt when damage dominates.",
        "de": "Arbeitswährung. AW ist der gutgeschriebene Wert geprüfter nützlicher Arbeit. Sie kann bezahlt, in ein Produkt gestapelt, besteuert, durch einen Gemeinfonds ausgegeben, bei Rückzahlung vernichtet oder bei Schaden zur Schuld werden.",
    },
    "P": {
        "en": "Price. P is the market payment claim for a good or service. It uses inputs, outputs, factor, quality, and scarcity, so it can differ from raw labour amount while still being anchored in work.",
        "de": "Preis. P ist die Marktzahlungsforderung für ein Gut oder eine Dienstleistung. Er nutzt Eingänge, Ausgänge, Faktor, Qualität und Knappheit und kann daher von bloßer Arbeitsmenge abweichen, bleibt aber an Arbeit gebunden.",
    },
    "S": {
        "en": "Scarcity factor. S rises when demand is high or supply is low, and falls when the market is oversupplied. It changes prices without pretending that old labour was performed a second time.",
        "de": "Knappheitsfaktor. S steigt, wenn Nachfrage hoch oder Angebot niedrig ist, und fällt bei Überangebot. Er verändert Preise, ohne so zu tun, als sei alte Arbeit ein zweites Mal geleistet worden.",
    },
    "ST": {
        "en": "Stack value. ST is accumulated AW inside a project or product. New verified work is placed on top of previous work, but the old layer is not counted again as newly created currency.",
        "de": "Stapelwert. ST ist angesammelte AW in einem Projekt oder Produkt. Neue geprüfte Arbeit wird oben auf vorherige Arbeit gelegt, aber die alte Schicht wird nicht erneut als neu erzeugte Währung gezählt.",
    },
    "α": {
        "en": "Input weight. α controls how strongly input units count in the price formula. It is lower than β in this simulation because consumed input matters, but useful output matters more.",
        "de": "Eingangsgewicht. α steuert, wie stark Eingangseinheiten in der Preisformel zählen. Es ist in dieser Simulation niedriger als β, weil verbrauchter Input zählt, aber nutzbarer Output stärker zählt.",
    },
    "β": {
        "en": "Output weight. β controls how strongly output units count in the price formula. Here β is the main price anchor because the economy pays for usable results, not only for consumed inputs.",
        "de": "Ausgangsgewicht. β steuert, wie stark Ausgangseinheiten in der Preisformel zählen. Hier ist β der wichtigste Preisanker, weil die Wirtschaft nutzbare Ergebnisse bezahlt, nicht nur verbrauchte Eingänge.",
    },
    "γ": {
        "en": "Damage weight. γ multiplies negative output before subtraction. A high γ means damage is considered severe and can overpower the positive side of the work block.",
        "de": "Schadensgewicht. γ multipliziert negativen Ausgang vor dem Abzug. Ein hohes γ bedeutet, dass Schaden als schwer gilt und die positive Seite des Arbeitsblocks überwiegen kann.",
    },
    "GF": {
        "en": "Public fund. GF is the common account used for infrastructure, verification, safety, education, resource repair, and public work. It receives transaction levies and resource rents, then pays shared labour.",
        "de": "Gemeinfonds. GF ist das gemeinsame Konto für Infrastruktur, Verifikation, Sicherheit, Bildung, Ressourcenpflege und öffentliche Arbeit. Er erhält Transaktionsabgaben und Ressourcenrenten und bezahlt daraus gemeinsame Arbeit.",
    },
    "GM": {
        "en": "Money supply. GM is the amount of labour currency circulating in the simulation. It rises through public creation or credit and falls through repayment or deliberate burning.",
        "de": "Geldmenge. GM ist die umlaufende Menge der Arbeitswährung in der Simulation. Sie steigt durch öffentliche Erzeugung oder Kredit und sinkt durch Rückzahlung oder gezielte Vernichtung.",
    },
    "T": {
        "en": "Transaction levy. T is a small share taken from market payments and moved into the public fund. It finances shared systems without pretending that the state created the original work.",
        "de": "Transaktionsabgabe. T ist ein kleiner Anteil von Marktzahlungen, der in den Gemeinfonds fließt. Sie finanziert gemeinsame Systeme, ohne so zu tun, als habe der Staat die ursprüngliche Arbeit erzeugt.",
    },
    "R": {
        "en": "Resource rent. R is paid when scarce or stressed natural resources are used. It pushes users to respect regeneration and returns part of natural value to the common system.",
        "de": "Ressourcenrente. R wird gezahlt, wenn knappe oder belastete Naturressourcen genutzt werden. Sie drängt Nutzer zur Beachtung von Regeneration und führt einen Teil des Naturwerts an das gemeinsame System zurück.",
    },
    "KR": {
        "en": "Credit. KR is temporary labour currency advanced for production or research before final sale. It must later be covered by output, repayment, or loss booking; otherwise it becomes unstable money creation.",
        "de": "Kredit. KR ist vorläufig bereitgestellte Arbeitswährung für Produktion oder Forschung vor dem endgültigen Verkauf. Er muss später durch Output, Rückzahlung oder Verlustbuchung gedeckt werden; sonst wird er instabile Geldschöpfung.",
    },
    "B": {
        "en": "Resource stock. B is the remaining amount of a natural or technical resource at the start or end of a period. It is the state variable that tells whether the system is being depleted or restored.",
        "de": "Bestand. B ist die verbleibende Menge einer natürlichen oder technischen Ressource zu Beginn oder Ende einer Periode. Er ist die Zustandsgröße, die zeigt, ob das System ausgelaugt oder wiederhergestellt wird.",
    },
    "REG": {
        "en": "Regeneration. REG is the amount by which a stock recovers in one period through natural growth, repair, maintenance, refilling, or ecological care.",
        "de": "Regeneration. REG ist die Menge, um die sich ein Bestand in einer Periode durch natürliches Wachstum, Reparatur, Wartung, Auffüllung oder ökologische Pflege erholt.",
    },
    "ENT": {
        "en": "Extraction. ENT is the amount taken from a resource stock for production or consumption. When ENT stays above REG for many periods, depletion pressure grows.",
        "de": "Entnahme. ENT ist die Menge, die einem Ressourcenbestand für Produktion oder Verbrauch entzogen wird. Wenn ENT über viele Perioden oberhalb von REG bleibt, wächst der Auslaugungsdruck.",
    },
    "SCH": {
        "en": "Damage. SCH is additional harm to a stock that is not normal extraction: pollution, destruction, erosion, contamination, or avoidable loss. It is counted separately because it should not look like productive use.",
        "de": "Schaden. SCH ist zusätzliche Belastung eines Bestands, die keine normale Entnahme ist: Verschmutzung, Zerstörung, Erosion, Kontamination oder vermeidbarer Verlust. Er wird getrennt gezählt, damit er nicht wie produktive Nutzung aussieht.",
    },
}


# =============================================================================
#  Model core
# =============================================================================

@dataclass(frozen=True)
class WorkType:
    name_en: str
    name_de: str
    factor: int
    short: str


WORK_TYPES: List[WorkType] = [
    WorkType("Agriculture / base work", "Ackerlandwirtschaft / Basisarbeit", 1, "Acker"),
    WorkType("Area work", "Flächenarbeit", 2, "Fläche"),
    WorkType("3D work / housebuilding", "3D-Arbeit / Häuserbau", 3, "3D"),
    WorkType("Time-critical work", "Zeitkritische Arbeit", 4, "Zeit"),
    WorkType("Causally important work", "Kausal wichtige Arbeit", 5, "Kausal"),
    WorkType("Mental work", "Geistige Arbeit", 6, "Geist"),
    WorkType("Communication work", "Kommunikationsarbeit", 7, "Komm"),
    WorkType("Decomposing the universe into blocks", "Das Universum in Blöcke zerlegen", 8, "Block"),
    WorkType("Mathematics", "Mathematik", 10, "Mathe"),
]


def work_type_name(wt: WorkType, lang: str) -> str:
    return wt.name_de if lang == "de" else wt.name_en


def stacked_factor(factors: Sequence[int]) -> float:
    """Additive stacking rule: 1 + sum(k_i - 1)."""
    if not factors:
        return 1.0
    return 1.0 + sum(float(k) - 1.0 for k in factors)


def clamp(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))


def jitter(rng: random.Random, base: float, spread: float) -> float:
    return base * (1.0 + rng.uniform(-spread, spread))


@dataclass
class WorkBlock:
    ident: int
    actor: str
    label_en: str
    label_de: str
    e: float
    o: float
    factors: List[int]
    q: float
    verified: bool = True
    negative: float = 0.0
    gamma: float = 1.5

    @property
    def label(self) -> Dict[str, str]:
        return {"en": self.label_en, "de": self.label_de}

    @property
    def m(self) -> float:
        return self.e + self.o

    @property
    def k(self) -> float:
        return stacked_factor(self.factors)

    @property
    def mwir(self) -> float:
        return self.e + self.o - self.gamma * self.negative

    @property
    def aw(self) -> float:
        if not self.verified:
            return 0.0
        return max(0.0, self.mwir) * self.k * self.q


@dataclass
class SimState:
    seed: int
    scenario: str
    blocks: List[WorkBlock] = field(default_factory=list)
    market_total: float = 0.0
    project_stack: float = 0.0
    public_fund: float = 3000.0
    money_supply: float = 20000.0
    public_created: float = 0.0
    taxes: float = 0.0
    resource_rent: float = 0.0
    credit_issued: float = 0.0
    credit_repaid: float = 0.0
    credit_debt: float = 0.0
    damage_debt: float = 0.0
    economy_total_aw: float = 0.0
    verification_reduced: int = 0
    verification_accepted: int = 0
    final_resource_stock: float = 1000.0
    last_market_max: str = ""
    last_scarcity_max: str = ""


@dataclass(frozen=True)
class Scenario:
    key: str
    food_s: float
    housing_s: float
    knowledge_s: float
    communication_s: float
    energy_s: float
    public_pressure: float
    credit_success: float
    extraction_pressure: float


SCENARIO_ALIASES = {
    "normal": "normal",
    "krise": "crisis",
    "crisis": "crisis",
    "forschung": "research",
    "research": "research",
    "hausbau": "housebuilding",
    "housebuilding": "housebuilding",
    "house": "housebuilding",
}


def normalize_scenario(name: str) -> str:
    key = (name or "normal").strip().lower()
    if key not in SCENARIO_ALIASES:
        allowed = ", ".join(sorted(SCENARIO_ALIASES.keys()))
        raise SystemExit("Unknown scenario '%s'. Allowed: %s" % (name, allowed))
    return SCENARIO_ALIASES[key]


def scenario_config(name: str) -> Scenario:
    key = normalize_scenario(name)
    if key == "crisis":
        return Scenario(key, food_s=2.25, housing_s=1.45, knowledge_s=1.30,
                        communication_s=1.90, energy_s=2.15, public_pressure=1.85,
                        credit_success=0.54, extraction_pressure=1.46)
    if key == "research":
        return Scenario(key, food_s=0.95, housing_s=1.05, knowledge_s=2.00,
                        communication_s=1.35, energy_s=1.05, public_pressure=1.18,
                        credit_success=0.80, extraction_pressure=0.88)
    if key == "housebuilding":
        return Scenario(key, food_s=1.05, housing_s=2.10, knowledge_s=1.25,
                        communication_s=1.25, energy_s=1.28, public_pressure=1.28,
                        credit_success=0.70, extraction_pressure=1.20)
    return Scenario(key, food_s=1.10, housing_s=1.15, knowledge_s=1.20,
                    communication_s=1.10, energy_s=1.05, public_pressure=1.00,
                    credit_success=0.68, extraction_pressure=1.00)


# =============================================================================
#  Section framework: explanation → local unit descriptions → art → simulation → summary
# =============================================================================

@dataclass(frozen=True)
class SectionSpec:
    key: str
    title_en: str
    title_de: str
    why_en: str
    why_de: str
    units: Tuple[str, ...]
    palette: Tuple[int, ...]
    art_factory: Callable[[UI, str], Sequence[str]]

    def title(self, lang: str) -> str:
        return self.title_de if lang == "de" else self.title_en

    def why(self, lang: str) -> str:
        return self.why_de if lang == "de" else self.why_en


def explain_units(ui: UI, lang: str, units: Sequence[str]) -> None:
    for key in units:
        prefix = "  " + ui.unit(key) + " " + ui.c("=", fg=244, bold=True) + " "
        plain_prefix_len = len(ui.strip(prefix))
        width = max(50, ui.width - plain_prefix_len - 2)
        wrapped = textwrap.wrap(UNIT_INFO[key][lang], width=width) or [""]
        print(prefix + wrapped[0])
        continuation = " " * plain_prefix_len
        for line in wrapped[1:]:
            print(continuation + line)


def begin_section(ui: UI, lang: str, spec: SectionSpec) -> None:
    ui.title(spec.title(lang), bg=220 if lang == "en" else 214)
    ui.sub(L(lang, "what_why"), bg=54, fg=231)
    ui.wrap(spec.why(lang), indent=2)
    print()
    ui.sub(L(lang, "units_here"), bg=190, fg=16)
    explain_units(ui, lang, spec.units)
    print()
    ui.sub(L(lang, "art"), bg=93, fg=231)
    ui.print_art(spec.art_factory(ui, lang), palette=spec.palette)
    print()


def end_section(ui: UI, lang: str, result_text: str, possible: Sequence[str]) -> None:
    print()
    ui.sub(L(lang, "summary"), bg=220, fg=16)
    ui.wrap(result_text, indent=2)
    print()
    ui.sub(L(lang, "possible"), bg=33, fg=231)
    for i, item in enumerate(possible):
        color = UI.RAINBOW[i % len(UI.RAINBOW)]
        ui.bullet(item, color=color, indent=2)
    print()


# =============================================================================
#  UTF-8 art factories
# =============================================================================

def art_banner(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╔══════════════════════════════════════════════════════════════════════╗",
        "║     ◈◈◈  LABOUR → BLOCKS → STACKS → CURRENCY → MARKETS  ◈◈◈       ║" if lang == "en" else "║     ◈◈◈  ARBEIT → BLÖCKE → STAPEL → WÄHRUNG → MÄRKTE  ◈◈◈        ║",
        "║                                                                      ║",
        "║        ███╗   ███╗  ╔═╗ ╦ ╦   ╦═╗ ╦  ╔═╗ ╔═╗ ╦╔═  ╔═╗              ║",
        "║        ████╗ ████║  ╠═╣ ║║║   ╠╦╝ ║  ║ ║ ║   ╠╩╗  ╚═╗              ║",
        "║        ██╔████╔██║  ╩ ╩ ╚╩╝   ╩╚═ ╩═╝ ╚═╝ ╚═╝ ╩ ╩  ╚═╝              ║",
        "║                                                                      ║",
        "║      ░▒▓█  every unit has a color, every section has a scene  █▓▒░   ║" if lang == "en" else "║      ░▒▓█  jede Einheit hat Farbe, jeder Teil hat eine Szene  █▓▒░   ║",
        "╚══════════════════════════════════════════════════════════════════════╝",
    ]


def art_factors(ui: UI, lang: str) -> Sequence[str]:
    return [
        "                         ╔════════════╗",
        "                         ║ MATHE ×10  ║",
        "                    ╔════╩════════════╩════╗",
        "                    ║ BLOCKZERLEGUNG ×8    ║" if lang == "de" else "                    ║ BLOCK DECOMPOSE ×8    ║",
        "               ╔════╩══════════════════════╩════╗",
        "               ║ KOMMUNIKATION ×7  |  GEIST ×6  ║" if lang == "de" else "               ║ COMMUNICATION ×7 | MENTAL ×6   ║",
        "          ╔════╩═════════════════════════════════╩════╗",
        "          ║ KAUSAL ×5 | ZEIT ×4 | 3D ×3 | FLÄCHE ×2   ║" if lang == "de" else "          ║ CAUSAL ×5 | TIME ×4 | 3D ×3 | AREA ×2      ║",
        "     ╔════╩════════════════════════════════════════════╩════╗",
        "     ║                 BASIS / ACKER ×1                     ║" if lang == "de" else "     ║                 BASE / FARMING ×1                    ║",
        "     ╚═══════════════════════════════════════════════════════╝",
        "          ▲ factor tower: higher layers carry stronger leverage ▲" if lang == "en" else "          ▲ Faktorenturm: obere Schichten tragen stärkere Hebelwirkung ▲",
    ]


def art_work(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╭────────────────────────────────────────────────────────────────────╮",
        "│  ┌───────┐     ╭────────────╮     ┌─────────┐     ╔══════════╗     │",
        "│  │ INPUT │ ──▶ │ TRANSFORM  │ ──▶ │ OUTPUT  │ ──▶ ║  CREDIT  ║     │" if lang == "en" else "│  │ INPUT │ ──▶ │ UMWANDLUNG │ ──▶ │ OUTPUT  │ ──▶ ║ GUTSCHR. ║     │",
        "│  └───────┘     ╰────────────╯     └─────────┘     ╚══════════╝     │",
        "│      ╲             ╭──────╮             ╱              ║            │",
        "│       ╲──────────▶ │  KQ  │ ◀──────────╱               ║            │",
        "│                    ╰──────╯                             ▼            │",
        "│                 measured work block becomes coloured AW              │" if lang == "en" else "│                 gemessener Arbeitsblock wird farbige AW               │",
        "╰────────────────────────────────────────────────────────────────────╯",
    ]


def art_project(ui: UI, lang: str) -> Sequence[str]:
    return [
        "                             ╱╲",
        "                            ╱  ╲",
        "                           ╱ ST ╲",
        "              ╔═══════════╧════╧═══════════╗",
        "              ║  roof layer: time + 3D     ║" if lang == "en" else "              ║  Dachschicht: Zeit + 3D    ║",
        "              ╠════════════════════════════╣",
        "              ║  walls: 3D work            ║" if lang == "en" else "              ║  Wände: 3D-Arbeit          ║",
        "              ╠════════════════════════════╣",
        "              ║  statics: mathematics      ║" if lang == "en" else "              ║  Statik: Mathematik        ║",
        "              ╠════════════════════════════╣",
        "              ║  ground: area + blocks     ║" if lang == "en" else "              ║  Boden: Fläche + Blöcke    ║",
        "              ╚════════════════════════════╝",
        "                 each new layer adds AW; old layers are not re-minted" if lang == "en" else "                 jede neue Schicht addiert AW; alte Schichten werden nicht neu geprägt",
    ]


def art_market(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╔══════════════════════════════════════════════════════════════════╗",
        "║             MARKET WHEEL / MARKTRAD                            ║",
        "║                                                                  ║",
        "║       α·E ─╮                                                    ║",
        "║            ├──▶ BASE PRICE CORE ──▶ ×K ─▶ ×Q ─▶ ×S ─▶ P         ║" if lang == "en" else "║            ├──▶ PREISKERN ───────▶ ×K ─▶ ×Q ─▶ ×S ─▶ P          ║",
        "║       β·O ─╯                                                    ║",
        "║                                                                  ║",
        "║     scarcity is a colored pressure ring around work value        ║" if lang == "en" else "║     Knappheit ist ein farbiger Druckring um den Arbeitswert       ║",
        "╚══════════════════════════════════════════════════════════════════╝",
    ]


def art_fund(ui: UI, lang: str) -> Sequence[str]:
    return [
        "                 ╔════════════════════════════════╗",
        "      T  ───────▶║                                ║",
        "                 ║        PUBLIC FUND / GF        ║" if lang == "en" else "                 ║        GEMEINFONDS / GF        ║",
        "      R  ───────▶║                                ║",
        "                 ╚═══════╦══════════════╦════════╝",
        "                         ║              ║",
        "                         ▼              ▼",
        "                  public work        GM control" if lang == "en" else "                  öffentliche Arbeit  GM-Steuerung",
        "                    ╭──────╮          ╭──────╮",
        "                    │  AW  │          │  GM  │",
        "                    ╰──────╯          ╰──────╯",
    ]


def art_credit(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╭────────────────────────────── WAREHOUSE ─────────────────────────────╮" if lang == "en" else "╭────────────────────────────── LAGERHAUS ──────────────────────────────╮",
        "│       KR enters before a buyer exists                                 │" if lang == "en" else "│       KR fließt hinein, bevor ein Käufer existiert                     │",
        "│                                                                       │",
        "│   ╔══════╗        ╔════════════╗        ╔════════════╗                │",
        "│   ║  KR  ║ ─────▶ ║ PRODUCT    ║ ─────▶ ║ SALE / P   ║                │" if lang == "en" else "│   ║  KR  ║ ─────▶ ║ PRODUKT    ║ ─────▶ ║ VERKAUF/P  ║                │",
        "│   ╚══════╝        ╚════════════╝        ╚══════╦═════╝                │",
        "│          ╲                 ▲                    ║                      │",
        "│           ╲──── loss debt ─╯                    ▼                      │" if lang == "en" else "│           ╲──── Verlustschuld ─╯                 ▼                      │",
        "│                                      repayment burns KR/GM             │" if lang == "en" else "│                                      Rückzahlung verbrennt KR/GM        │",
        "╰───────────────────────────────────────────────────────────────────────╯",
    ]


def art_resources(ui: UI, lang: str) -> Sequence[str]:
    return [
        "             🌱 REG                         ☁ SCH",
        "              ╲                              ╱",
        "               ╲                            ╱",
        "        ╔══════════════════════════════════════════╗",
        "        ║            RESOURCE STOCK B              ║" if lang == "en" else "        ║            RESSOURCENBESTAND B           ║",
        "        ╚══════════════════════════════════════════╝",
        "                 ╲                         ╱",
        "                  ╲                       ╱",
        "                   ▼                     ▼",
        "                  ENT                  R if overused" if lang == "en" else "                  ENT                  R bei Übernutzung",
        "        water, soil, forest, energy, attention: stocks must not vanish" if lang == "en" else "        Wasser, Boden, Wald, Energie, Aufmerksamkeit: Bestände dürfen nicht verschwinden",
    ]


def art_damage(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╔════════════════════════════════════════════════════════════════════╗",
        "║                         DAMAGE GATE                               ║" if lang == "en" else "║                         SCHADENSTOR                               ║",
        "║                                                                    ║",
        "║       E + O+ ───────────────┐                                      ║",
        "║                             ├──▶ Mwir ───▶ K ───▶ Q ───▶ AW        ║",
        "║       γ · O- ── subtract ───┘                                      ║" if lang == "en" else "║       γ · O- ── abziehen ───┘                                      ║",
        "║                                                                    ║",
        "║        if the shadow side is larger, debt appears instead of value  ║" if lang == "en" else "║        ist die Schattenseite größer, entsteht Schuld statt Wert     ║",
        "╚════════════════════════════════════════════════════════════════════╝",
    ]


def art_periods(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╔════════════════════════════════════════════════════════════════════╗",
        "║  PERIOD LOOP                                                      ║" if lang == "en" else "║  PERIODENSCHLEIFE                                                 ║",
        "║                                                                    ║",
        "║  demand → scarcity → sector work → price → levy → fund → stabilise ║" if lang == "en" else "║  Nachfrage → Knappheit → Sektorarbeit → Preis → Abgabe → Fonds → Stabilisierung ║",
        "║                                                                    ║",
        "║       ╭──────╮    ╭──────╮    ╭──────╮    ╭──────╮                 ║",
        "║ t=1 ▶ │ AW/P │ ▶ │ T/GF │ ▶ │ GM/S │ ▶ │ next │ ──▶ t+1           ║" if lang == "en" else "║ t=1 ▶ │ AW/P │ ▶ │ T/GF │ ▶ │ GM/S │ ▶ │ weiter │ ─▶ t+1          ║",
        "║       ╰──────╯    ╰──────╯    ╰──────╯    ╰──────╯                 ║",
        "╚════════════════════════════════════════════════════════════════════╝",
    ]


def art_verification(ui: UI, lang: str) -> Sequence[str]:
    return [
        "                         ╔══════════════╗",
        "         claimed K,Q ──▶ ║  CHECKROOM   ║ ──▶ verified AW" if lang == "en" else "         behauptet K,Q ─▶║  PRÜFRAUM    ║ ──▶ geprüfte AW",
        "                         ╚══════╦═══════╝",
        "                                ║",
        "             ╔══════════════════╩══════════════════╗",
        "             ║ proof? recipient effect? causality? ║" if lang == "en" else "             ║ Beweis? Empfängerwirkung? Kausalität? ║",
        "             ╚══════════════════╦══════════════════╝",
        "                    accept  ────╬──── reduce ──── reject" if lang == "en" else "                    bestätigen ─╬──── kürzen ──── ablehnen",
        "                                ▼",
        "                       coloured ledger result" if lang == "en" else "                       farbiges Registerergebnis",
    ]


def art_final(ui: UI, lang: str) -> Sequence[str]:
    return [
        "╔════════════════════════════════════════════════════════════════════╗",
        "║                      FINAL LEDGER CONSTELLATION                   ║" if lang == "en" else "║                      SCHLUSS-KONTENSTERN                          ║",
        "║                                                                    ║",
        "║       AW stars     ST house      GF treasury      GM circulation   ║" if lang == "en" else "║       AW-Sterne    ST-Haus      GF-Kasse        GM-Umlauf          ║",
        "║          ✦            ⌂              ◈                ◎            ║",
        "║                                                                    ║",
        "║       T rivers     R earth-rent   KR shadow      damage debt       ║" if lang == "en" else "║       T-Flüsse     R-Erdrente    KR-Schatten     Schadensschuld    ║",
        "║          ≋             ▣             ◌                ⚠            ║",
        "╚════════════════════════════════════════════════════════════════════╝",
    ]


# =============================================================================
#  Section specs
# =============================================================================

SPECS: Dict[str, SectionSpec] = {
    "factors": SectionSpec(
        "factors",
        "1) Value scale of work types",
        "1) Wertskala der Arbeitsarten",
        "The simulation begins with the fixed hierarchy of work factors. This matters because every later work block uses K to turn raw measured work into higher or lower labour currency according to leverage and responsibility.",
        "Die Simulation beginnt mit der festen Hierarchie der Arbeitsfaktoren. Das ist wichtig, weil jeder spätere Arbeitsblock K nutzt, um rohe gemessene Arbeit je nach Hebelwirkung und Verantwortung in mehr oder weniger Arbeitswährung zu verwandeln.",
        ("K", "3D"), tuple(UI.VIOLET), art_factors),
    "work": SectionSpec(
        "work",
        "2) Individual coloured work blocks",
        "2) Einzelne farbige Arbeitsblöcke",
        "This part creates separate jobs and tests the base currency rule: input and output form the work amount, the work factor scales it, quality validates it, and only verified useful work becomes AW.",
        "Dieser Teil erzeugt einzelne Arbeiten und prüft die Grundregel der Währung: Eingang und Ausgang bilden die Arbeitsmenge, der Arbeitsfaktor skaliert sie, Qualität bestätigt sie, und nur geprüfte nützliche Arbeit wird AW.",
        ("ID", "E", "O", "M", "K", "Q", "AW"), tuple(UI.RAINBOW), art_work),
    "project": SectionSpec(
        "project",
        "3) Project stack: a house made of labour layers",
        "3) Projektstapel: ein Haus aus Arbeitsschichten",
        "A product is not a single number. This part stacks several verified segments into one project value and shows why old work must not be counted again as newly created currency.",
        "Ein Produkt ist nicht nur eine einzelne Zahl. Dieser Teil stapelt mehrere geprüfte Segmente zu einem Projektwert und zeigt, warum alte Arbeit nicht erneut als neu erzeugte Währung gezählt werden darf.",
        ("ID", "M", "K", "Q", "AW", "ST"), tuple(UI.FIRE), art_project),
    "market": SectionSpec(
        "market",
        "4) Market price wheel with scarcity pressure",
        "4) Marktpreisrad mit Knappheitsdruck",
        "This part separates labour value from market price. Price still starts from work, but input weight, output weight, quality and scarcity decide what the market actually pays.",
        "Dieser Teil trennt Arbeitswert und Marktpreis. Der Preis beginnt weiter bei Arbeit, aber Eingangsgewicht, Ausgangsgewicht, Qualität und Knappheit entscheiden, was der Markt tatsächlich zahlt.",
        ("α", "β", "E", "O", "K", "Q", "S", "P"), tuple(UI.WATER), art_market),
    "fund": SectionSpec(
        "fund",
        "5) Public fund and currency steering",
        "5) Gemeinfonds und Währungssteuerung",
        "This part simulates the common account. Transaction levies and resource rents flow in, public work flows out, and the money supply changes only when the public side must create or remove AW.",
        "Dieser Teil simuliert das gemeinsame Konto. Transaktionsabgaben und Ressourcenrenten fließen hinein, öffentliche Arbeit fließt hinaus, und die Geldmenge ändert sich nur, wenn die öffentliche Seite AW erzeugen oder entfernen muss.",
        ("T", "R", "GF", "AW", "GM"), tuple(UI.WATER), art_fund),
    "credit": SectionSpec(
        "credit",
        "6) Production credit and unsold warehouse goods",
        "6) Produktionskredit und unverkaufte Lagerware",
        "This part tests whether temporary credit becomes real value. A producer receives KR before the buyer exists; success turns it into sale revenue and repayment, failure leaves debt.",
        "Dieser Teil prüft, ob vorläufiger Kredit zu realem Wert wird. Ein Produzent erhält KR, bevor der Käufer existiert; Erfolg wird Verkaufserlös und Rückzahlung, Misserfolg bleibt Schuld.",
        ("KR", "Q", "P", "AW"), tuple(UI.FIRE), art_credit),
    "resources": SectionSpec(
        "resources",
        "7) Resource stock and ecological feedback",
        "7) Ressourcenbestand und ökologische Rückkopplung",
        "This part gives nature its own ledger. The stock changes through regeneration, extraction and damage; overuse creates rent so the economy sees depletion instead of hiding it.",
        "Dieser Teil gibt der Natur ein eigenes Register. Der Bestand verändert sich durch Regeneration, Entnahme und Schaden; Übernutzung erzeugt Rente, damit die Wirtschaft Auslaugung sieht, statt sie zu verstecken.",
        ("B", "REG", "ENT", "SCH", "R"), tuple(UI.FOREST), art_resources),
    "damage": SectionSpec(
        "damage",
        "8) Negative work and damage subtraction",
        "8) Negative Arbeit und Schadensabzug",
        "This part prevents effort worship. A person can spend effort and still create harm; negative output is subtracted before AW is credited, and serious harm can become debt.",
        "Dieser Teil verhindert Aufwandsgläubigkeit. Jemand kann sich anstrengen und trotzdem Schaden erzeugen; negativer Ausgang wird vor der AW-Gutschrift abgezogen, und schwerer Schaden kann Schuld werden.",
        ("E", "O+", "O-", "γ", "Mwir", "K", "Q", "AW"), tuple(UI.FIRE), art_damage),
    "periods": SectionSpec(
        "periods",
        "9) Multi-period economy with sectors",
        "9) Mehrperioden-Wirtschaft mit Sektoren",
        "This part runs the economy through several periods. Sector work creates AW and prices, scarcity moves, levies feed the public fund, and currency circulation changes over time.",
        "Dieser Teil lässt die Wirtschaft über mehrere Perioden laufen. Sektorarbeit erzeugt AW und Preise, Knappheit bewegt sich, Abgaben füttern den Gemeinfonds, und der Währungsumlauf ändert sich über die Zeit.",
        ("K", "Q", "S", "AW", "P", "T", "GF", "GM"), tuple(UI.RAINBOW), art_periods),
    "verification": SectionSpec(
        "verification",
        "10) Verification gate against factor fraud",
        "10) Prüfungstor gegen Faktorbetrug",
        "This part tests claimed high-value work. Verification can confirm, reduce, or reject claims so meetings are not automatically communication value and wrong mathematics is not paid as mathematics.",
        "Dieser Teil prüft behauptete Hochwertarbeit. Verifikation kann Ansprüche bestätigen, kürzen oder ablehnen, damit Meetings nicht automatisch Kommunikationswert sind und falsche Mathematik nicht als Mathematik bezahlt wird.",
        ("ID", "M", "K", "Q", "AW"), tuple(UI.VIOLET), art_verification),
    "final": SectionSpec(
        "final",
        "11) Final ledger constellation",
        "11) Schluss-Kontenstern",
        "The last part joins the important balances. It checks whether the simulation produced useful work, stable public accounts, controlled credit, visible resource pressure, and accountable damage.",
        "Der letzte Teil führt die wichtigen Konten zusammen. Er prüft, ob die Simulation nützliche Arbeit, stabile öffentliche Konten, kontrollierten Kredit, sichtbaren Ressourcendruck und zurechenbaren Schaden erzeugt hat.",
        ("AW", "ST", "GF", "GM", "T", "R", "KR"), tuple(UI.RAINBOW), art_final),
}


# =============================================================================
#  Simulation parts
# =============================================================================

def part_banner(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int) -> None:
    ui.rule("█", UI.RAINBOW)
    print(ui.rainbow("  " + L(lang, "program_title") + "  ", UI.RAINBOW))
    print("  " + ui.c(L(lang, "subtitle"), fg=220, bold=True))
    ui.rule("█", UI.RAINBOW)
    ui.print_art(art_banner(ui, lang), palette=UI.RAINBOW)
    print()
    intro = (
        "The program prints the UTF-8 art directly to the terminal. Every simulation part explains only the units used in that part, then shows a colorful scene, calculates values, and evaluates the possible outcomes."
        if lang == "en" else
        "Das Programm druckt die UTF-8-Kunst direkt ins Terminal. Jeder Simulationsteil erklärt nur die Einheiten dieses Teils, zeigt dann eine farbige Szene, berechnet Werte und wertet mögliche Ausgänge aus."
    )
    ui.wrap(intro, indent=2)
    print()
    ui.kv(L(lang, "language"), ui.c("English" if lang == "en" else "Deutsch", fg=220, bold=True))
    ui.kv(L(lang, "scenario"), ui.c(L(lang, "scenario_" + cfg.key), fg=201, bold=True))
    ui.kv(L(lang, "periods"), ui.c(str(periods), fg=82, bold=True))
    ui.kv(L(lang, "seed"), ui.c(str(state.seed), fg=213, bold=True))
    print()


def part_factor_scale(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["factors"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    rows = []
    for wt in WORK_TYPES:
        marker = ui.unit("3D") if wt.short == "3D" else wt.short
        rows.append([work_type_name(wt, lang), marker, ui.amount(wt.factor, "K", 0)])
    headers = ["work type", "short", "K"] if lang == "en" else ["Arbeitsart", "kurz", "K"]
    ui.table(headers, rows, right=[2])
    print()
    ui.kv(L(lang, "formula"), "K(combined) = 1 + Σ(kᵢ − 1)")
    result = (
        "The factor tower establishes the economy's value grammar: base farming stays at K=1, 3D construction is K=3, and mathematics reaches K=10. The additive stacking rule keeps high-value combinations powerful but bounded."
        if lang == "en" else
        "Der Faktorenturm legt die Wertgrammatik der Wirtschaft fest: Basis-Ackerarbeit bleibt bei K=1, 3D-Konstruktion liegt bei K=3, und Mathematik erreicht K=10. Die additive Stapelregel macht Kombinationen stark, aber begrenzt."
    )
    possible = (
        [
            "Stable outcome: K separates simple, spatial, communicative and mathematical work without multiplying them into absurd numbers.",
            "Inflationary outcome: if actors can claim K without verification, too many blocks jump into high factors and AW becomes too easy to create.",
            "Productive outcome: education and better tools move people from low K work into higher leverage work without devaluing food and basic supply.",
        ] if lang == "en" else [
            "Stabiler Ausgang: K trennt einfache, räumliche, kommunikative und mathematische Arbeit, ohne sie in absurde Zahlen zu multiplizieren.",
            "Inflationärer Ausgang: Wenn Akteure K ohne Prüfung behaupten dürfen, springen zu viele Blöcke in hohe Faktoren und AW wird zu leicht erzeugt.",
            "Produktiver Ausgang: Bildung und bessere Werkzeuge bewegen Menschen von niedrigem K in höhere Hebelarbeit, ohne Nahrung und Grundversorgung zu entwerten.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_work_blocks(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["work"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)

    actors = ["Ada", "Bela", "Cem", "Daria", "Elif", "Farid", "Gita", "Mira"]
    templates = [
        ("Harvest", "Ernte", [1], 22, 85, 0.12),
        ("Area plan", "Flächenplan", [2], 16, 64, 0.10),
        ("Raw structure", "Rohbau", [3], 50, 130, 0.16),
        ("Rescue repair", "Rettungsreparatur", [3, 4, 5], 38, 96, 0.22),
        ("Diagnosis", "Diagnose", [6, 5], 18, 72, 0.18),
        ("Team coordination", "Teamkoordination", [7], 12, 58, 0.15),
        ("Block model", "Blockmodell", [8], 20, 70, 0.17),
        ("Algorithm", "Algorithmus", [10], 15, 78, 0.20),
    ]
    rows: List[List[object]] = []
    for i in range(1, 15):
        label_en, label_de, factors, base_e, base_o, spread = rng.choice(templates)
        e = jitter(rng, base_e, spread)
        o = jitter(rng, base_o, spread)
        q = clamp(rng.gauss(1.03, 0.18), 0.45, 1.58)
        verified = rng.random() > 0.065
        block = WorkBlock(i, rng.choice(actors), label_en, label_de, e, o, list(factors), q, verified)
        state.blocks.append(block)
        aw_cell = ui.amount(block.aw, "AW") if verified else ui.c(" %s " % L(lang, "rejected"), fg=231, bg=196, bold=True)
        rows.append([
            ui.amount(block.ident, "ID", 0),
            block.actor,
            block.label[lang],
            ui.amount(block.e, "E"),
            ui.amount(block.o, "O"),
            ui.amount(block.m, "M"),
            ui.amount(block.k, "K", 1),
            ui.amount(block.q, "Q", 2),
            aw_cell,
        ])
    headers = ["ID", "actor", "work", "E", "O", "M", "K", "Q", "AW"] if lang == "en" else ["ID", "Akteur", "Arbeit", "E", "O", "M", "K", "Q", "AW"]
    ui.table(headers, rows, right=[3, 4, 5, 6, 7, 8])
    block_aw = sum(b.aw for b in state.blocks)
    top = max(state.blocks, key=lambda b: b.aw)
    rejected = sum(1 for b in state.blocks if not b.verified)
    print()
    ui.kv(L(lang, "formula"), "%s = (%s + %s) · %s · %s" % (ui.unit("AW"), ui.unit("E"), ui.unit("O"), ui.unit("K"), ui.unit("Q")))
    ui.kv(L(lang, "result"), ui.amount(block_aw, "AW"))
    result = (
        "The work-block scene produced %s from %d blocks. The strongest credited block was '%s' with %s. %d block(s) were rejected, showing that effort alone does not mint currency." %
        (ui.strip(ui.amount(block_aw, "AW")), len(state.blocks), top.label[lang], ui.strip(ui.amount(top.aw, "AW")), rejected)
        if lang == "en" else
        "Die Arbeitsblock-Szene erzeugte %s aus %d Blöcken. Der stärkste gutgeschriebene Block war '%s' mit %s. %d Block/Blöcke wurden abgelehnt; Aufwand allein prägt also keine Währung." %
        (ui.strip(ui.amount(block_aw, "AW")), len(state.blocks), top.label[lang], ui.strip(ui.amount(top.aw, "AW")), rejected)
    )
    possible = (
        [
            "High-quality outcome: if Q rises while K is justified, AW grows without fraud because the useful output is better.",
            "Weak-output outcome: if O is low, the block stays small even when a worker spent many inputs.",
            "Verification failure: if a claimed block cannot be verified, AW becomes zero and the ledger remains clean.",
        ] if lang == "en" else [
            "Hochwertiger Ausgang: Wenn Q steigt und K berechtigt ist, wächst AW ohne Betrug, weil der nützliche Output besser ist.",
            "Schwacher Output: Wenn O niedrig ist, bleibt der Block klein, selbst wenn viele Eingänge verbraucht wurden.",
            "Prüfversagen: Wenn ein behaupteter Block nicht verifiziert werden kann, wird AW null und das Register bleibt sauber.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_project_stack(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["project"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    segments = [
        ("S1", "grid ground", "Grundstück rastern", 160, [2, 8], 1.00),
        ("S2", "pour foundation", "Fundament gießen", 280, [3], 1.08),
        ("S3", "build 3D shell", "3D-Rohbau", 900, [3], 0.96),
        ("S4", "calculate statics", "Statik berechnen", 85, [10], 1.22),
        ("S5", "construction communication", "Baukommunikation", 120, [7, 5], 1.10),
        ("S6", "seal roof quickly", "Dach zeitkritisch abdichten", 210, [3, 4], 1.02),
        ("S7", "final inspection", "Endprüfung", 70, [6, 5], 1.00),
    ]
    stack = 0.0
    rows: List[List[object]] = []
    best = ("", 0.0)
    for sid, name_en, name_de, m, factors, q in segments:
        k = stacked_factor(factors)
        aw = m * k * q
        stack += aw
        label = name_de if lang == "de" else name_en
        if aw > best[1]:
            best = (label, aw)
        rows.append([
            ui.c(sid, fg=250, bold=True), label, ui.amount(m, "M"), ui.amount(k, "K", 1),
            ui.amount(q, "Q", 2), ui.amount(aw, "AW"), ui.amount(stack, "ST")
        ])
    state.project_stack = stack
    headers = ["ID", "segment", "M", "K", "Q", "AW", "ST"] if lang == "en" else ["ID", "Segment", "M", "K", "Q", "AW", "ST"]
    ui.table(headers, rows, right=[2, 3, 4, 5, 6])
    print()
    ui.kv(L(lang, "formula"), "%s(new) = %s(old) + %s(new layer)" % (ui.unit("ST"), ui.unit("ST"), ui.unit("AW")))
    ui.kv(L(lang, "result"), ui.amount(stack, "ST"))
    result = (
        "The house stack ends at %s. The largest layer is '%s' with %s. The key rule is visible: each layer adds new AW, but the previous stack is carried forward, not minted again." %
        (ui.strip(ui.amount(stack, "ST")), best[0], ui.strip(ui.amount(best[1], "AW")))
        if lang == "en" else
        "Der Hausstapel endet bei %s. Die größte Schicht ist '%s' mit %s. Die Kernregel ist sichtbar: Jede Schicht addiert neue AW, aber der vorherige Stapel wird nur mitgetragen, nicht neu geprägt." %
        (ui.strip(ui.amount(stack, "ST")), best[0], ui.strip(ui.amount(best[1], "AW")))
    )
    possible = (
        [
            "Strong construction outcome: high-Q 3D layers dominate the stack because physical volume work is large.",
            "Planning leverage outcome: a small mathematical or communication segment can matter more than its size when K is high.",
            "Anti-inflation outcome: if the same wall is sold later, only new work is added; the old ST is not counted again.",
        ] if lang == "en" else [
            "Starker Bauausgang: 3D-Schichten mit hohem Q dominieren den Stapel, weil räumliche Arbeit groß ist.",
            "Planungshebel: Ein kleines mathematisches oder kommunikatives Segment kann wegen hohem K stärker wirken als seine Größe vermuten lässt.",
            "Anti-Inflations-Ausgang: Wenn dieselbe Wand später verkauft wird, zählt nur neue Arbeit; der alte ST wird nicht erneut gezählt.",
        ]
    )
    end_section(ui, lang, result, possible)


@dataclass
class MarketRow:
    name: str
    e: float
    o: float
    k: float
    q: float
    s: float
    p: float


def part_market(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["market"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    alpha = 0.50
    beta = 1.00
    goods = [
        ("potato basket", "Kartoffelkorb", 40, 120, 1, 1.00, cfg.food_s),
        ("house module", "Hausmodul", 130, 350, 3, 1.10, cfg.housing_s),
        ("power-node repair", "Stromknoten-Reparatur", 25, 80, stacked_factor([3, 4, 5]), 1.04, cfg.energy_s),
        ("math algorithm", "Mathe-Algorithmus", 20, 90, 10, 1.22, cfg.knowledge_s),
        ("team alignment", "Teamabstimmung", 15, 60, 7, 1.12, cfg.communication_s),
    ]
    rows: List[List[object]] = []
    total = 0.0
    market_rows: List[MarketRow] = []
    for en, de, e, o, k, q, s in goods:
        p = (alpha * e + beta * o) * k * q * s
        total += p
        name = de if lang == "de" else en
        market_rows.append(MarketRow(name, e, o, k, q, s, p))
        rows.append([name, ui.amount(e, "E"), ui.amount(o, "O"), ui.amount(k, "K", 1),
                     ui.amount(q, "Q"), ui.amount(s, "S") + " " + ui.heat(s, lang=lang), ui.amount(p, "P")])
    state.market_total = total
    max_price = max(market_rows, key=lambda x: x.p)
    max_s = max(market_rows, key=lambda x: x.s)
    state.last_market_max = max_price.name
    state.last_scarcity_max = max_s.name
    ui.kv(L(lang, "formula"), "%s = (%s·%s + %s·%s) · %s · %s · %s" % (ui.unit("P"), ui.unit("α"), ui.unit("E"), ui.unit("β"), ui.unit("O"), ui.unit("K"), ui.unit("Q"), ui.unit("S")))
    ui.kv("α / β", "%s = %s   %s = %s" % (ui.unit("α"), ui.c(alpha, fg=39, bold=True), ui.unit("β"), ui.c(beta, fg=77, bold=True)))
    print()
    headers = ["good", "E", "O", "K", "Q", "S", "P"] if lang == "en" else ["Gut", "E", "O", "K", "Q", "S", "P"]
    ui.table(headers, rows, right=[1, 2, 3, 4, 5, 6])
    print()
    ui.kv(L(lang, "result"), ui.amount(total, "P"))
    result = (
        "The market scene produced total price volume %s. The highest price item was '%s', while the strongest scarcity pressure appeared at '%s'. This proves that P is work-anchored but scarcity-sensitive." %
        (ui.strip(ui.amount(total, "P")), max_price.name, max_s.name)
        if lang == "en" else
        "Die Marktszene erzeugte ein Preisvolumen von %s. Der höchste Preis lag bei '%s', während der stärkste Knappheitsdruck bei '%s' erschien. Das zeigt: P ist arbeitsgebunden, aber knappheitsempfindlich." %
        (ui.strip(ui.amount(total, "P")), max_price.name, max_s.name)
    )
    possible = (
        [
            "Crisis outcome: high S makes food, energy or repair prices jump even when their base work type is not the highest.",
            "Research outcome: high K and Q in knowledge work can become expensive even with small E and O.",
            "Oversupply outcome: if S falls below 1, price drops without deleting the old work record.",
        ] if lang == "en" else [
            "Krisenausgang: Hohes S lässt Nahrung, Energie oder Reparaturen springen, selbst wenn ihre Arbeitsart nicht die höchste ist.",
            "Forschungsausgang: Hohes K und Q in Wissensarbeit kann teuer werden, obwohl E und O klein sind.",
            "Überangebotsausgang: Wenn S unter 1 fällt, sinkt der Preis, ohne den alten Arbeitsnachweis zu löschen.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_public_fund(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["fund"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    if state.market_total <= 0:
        state.market_total = 2500.0
    start_gf = state.public_fund
    start_gm = state.money_supply
    t = 0.05 * state.market_total
    r = 185.0 * cfg.extraction_pressure + 35.0 * cfg.energy_s
    public_work = 800.0 * cfg.public_pressure
    created = max(0.0, public_work - t - r)
    burned = max(0.0, (t + r - public_work) * 0.35)
    state.taxes += t
    state.resource_rent += r
    state.public_created += created
    state.public_fund = start_gf + t + r - public_work
    state.money_supply = start_gm + created - burned
    rows = [
        [L(lang, "start"), "public opening balance" if lang == "en" else "öffentlicher Anfangsstand", "", ui.amount(start_gf, "GF"), ui.amount(start_gm, "GM")],
        [L(lang, "income"), "market levy" if lang == "en" else "Marktabgabe", ui.amount(t, "T"), ui.amount(start_gf + t, "GF"), ui.amount(start_gm, "GM")],
        [L(lang, "income"), "resource use" if lang == "en" else "Ressourcennutzung", ui.amount(r, "R"), ui.amount(start_gf + t + r, "GF"), ui.amount(start_gm, "GM")],
        [L(lang, "expense"), "shared work" if lang == "en" else "gemeinsame Arbeit", ui.amount(-public_work, "AW", signed=True), ui.amount(state.public_fund, "GF"), ui.amount(start_gm, "GM")],
        [L(lang, "control"), "newly issued" if lang == "en" else "neu erzeugt", ui.amount(created, "AW"), ui.amount(state.public_fund, "GF"), ui.amount(start_gm + created, "GM")],
        [L(lang, "control"), "burned" if lang == "en" else "verbrannt", ui.amount(-burned, "AW", signed=True), ui.amount(state.public_fund, "GF"), ui.amount(state.money_supply, "GM")],
    ]
    headers = ["type", "process", "amount", "GF", "GM"] if lang == "en" else ["Art", "Vorgang", "Betrag", "GF", "GM"]
    ui.table(headers, rows, right=[2, 3, 4])
    net = state.money_supply - start_gm
    result = (
        "The public fund ends at %s and the money supply changes by %s. If public work is larger than public income, AW is newly issued; if income exceeds spending, part can be burned." %
        (ui.strip(ui.amount(state.public_fund, "GF")), ui.strip(ui.amount(net, "GM", signed=True)))
        if lang == "en" else
        "Der Gemeinfonds endet bei %s und die Geldmenge verändert sich um %s. Wenn öffentliche Arbeit größer ist als öffentliche Einnahmen, wird AW neu ausgegeben; wenn Einnahmen Ausgaben übersteigen, kann ein Teil verbrannt werden." %
        (ui.strip(ui.amount(state.public_fund, "GF")), ui.strip(ui.amount(net, "GM", signed=True)))
    )
    possible = (
        [
            "Covered outcome: T and R pay for public work, so GM stays stable or even shrinks.",
            "Deficit outcome: public pressure is high, new AW enters GM, and later inflation control becomes important.",
            "Investment outcome: even if GM rises, infrastructure or verification can increase future real productivity.",
        ] if lang == "en" else [
            "Gedeckter Ausgang: T und R bezahlen öffentliche Arbeit, sodass GM stabil bleibt oder sogar sinkt.",
            "Defizitausgang: Öffentlicher Druck ist hoch, neue AW geht in GM, und spätere Inflationskontrolle wird wichtig.",
            "Investitionsausgang: Selbst wenn GM steigt, können Infrastruktur oder Verifikation die spätere reale Produktivität erhöhen.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_credit(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["credit"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    products = [
        ("tool warehouse", "Werkzeuglager", 620.0, 1.04),
        ("learning software", "Lernsoftware", 480.0, 1.18),
        ("brick series", "Bauziegel-Serie", 760.0, 0.96),
        ("sensor kit", "Sensorpaket", 540.0, 1.09),
        ("math prototype", "Mathe-Prototyp", 520.0, 1.24),
    ]
    rows: List[List[object]] = []
    sold = 0
    lost = 0
    for en, de, kr_base, q_base in products:
        kr = jitter(rng, kr_base, 0.12)
        q = clamp(jitter(rng, q_base, 0.10), 0.60, 1.48)
        success = rng.random() < cfg.credit_success
        state.credit_issued += kr
        state.money_supply += kr
        if success:
            sold += 1
            p = kr * (1.10 + 0.20 * q + rng.uniform(0.00, 0.18))
            repayment = min(kr, p * 0.80)
            gain = p - repayment
            state.credit_repaid += repayment
            state.money_supply -= repayment
            outcome = ui.c(" %s " % L(lang, "sold"), fg=16, bg=82, bold=True)
            result_aw = ui.amount(gain, "AW")
        else:
            lost += 1
            p = 0.0
            debt = kr * rng.uniform(0.65, 0.95)
            state.credit_debt += debt
            outcome = ui.c(" %s " % L(lang, "loss"), fg=231, bg=196, bold=True)
            result_aw = ui.amount(-debt, "AW", signed=True)
        rows.append([de if lang == "de" else en, ui.amount(kr, "KR"), ui.amount(q, "Q"), ui.amount(p, "P"), outcome, result_aw])
    headers = ["product", "KR", "Q", "P", "outcome", "AW"] if lang == "en" else ["Produkt", "KR", "Q", "P", "Ergebnis", "AW"]
    ui.table(headers, rows, right=[1, 2, 3, 5])
    result = (
        "%d product(s) sold and %d became warehouse losses. Total KR issued is %s, repayment is %s, and open debt is %s. Credit is useful, but only if output later validates it." %
        (sold, lost, ui.strip(ui.amount(state.credit_issued, "KR")), ui.strip(ui.amount(state.credit_repaid, "KR")), ui.strip(ui.amount(state.credit_debt, "AW")))
        if lang == "en" else
        "%d Produkt(e) wurden verkauft und %d wurden Lagerverluste. Insgesamt ausgegebener KR beträgt %s, Rückzahlung %s, offene Schuld %s. Kredit ist nützlich, aber nur, wenn späterer Output ihn bestätigt." %
        (sold, lost, ui.strip(ui.amount(state.credit_issued, "KR")), ui.strip(ui.amount(state.credit_repaid, "KR")), ui.strip(ui.amount(state.credit_debt, "AW")))
    )
    possible = (
        [
            "Successful inventory outcome: high Q and demand produce P, KR is repaid, and circulation is disciplined.",
            "Loss outcome: goods remain unsold, KR stays as debt, and the producer cannot call inventory value real money forever.",
            "Research option outcome: a prototype may fail now but create later knowledge value if verification and use arrive later.",
        ] if lang == "en" else [
            "Erfolgreicher Lagerausgang: Hohes Q und Nachfrage erzeugen P, KR wird zurückgezahlt, und der Umlauf bleibt diszipliniert.",
            "Verlustausgang: Ware bleibt unverkauft, KR bleibt Schuld, und der Produzent kann Lagerwert nicht ewig als echtes Geld behandeln.",
            "Forschungsoptions-Ausgang: Ein Prototyp kann jetzt scheitern, aber später Wissenswert erzeugen, wenn Prüfung und Nutzung nachkommen.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_resources(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["resources"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    b = 1000.0
    rows: List[List[object]] = []
    local_r = 0.0
    for t in range(1, periods + 1):
        reg = jitter(rng, 35.0, 0.18)
        ent = jitter(rng, 49.0 * cfg.extraction_pressure, 0.22)
        sch = max(0.0, jitter(rng, 9.5 * cfg.extraction_pressure, 0.35))
        overuse = max(0.0, ent + sch - reg)
        r = overuse * (2.8 + 0.03 * max(0.0, 1000.0 - b))
        b_new = max(0.0, b + reg - ent - sch)
        local_r += r
        rows.append([str(t), ui.amount(b, "B"), ui.amount(reg, "REG"), ui.amount(ent, "ENT"), ui.amount(sch, "SCH"), ui.amount(r, "R"), ui.amount(b_new, "B"), ui.heat((ent + sch) / max(1.0, reg), low=0.9, high=2.0, lang=lang)])
        b = b_new
    state.resource_rent += local_r
    state.final_resource_stock = b
    ui.kv(L(lang, "formula"), "%s(new) = %s(old) + %s − %s − %s" % (ui.unit("B"), ui.unit("B"), ui.unit("REG"), ui.unit("ENT"), ui.unit("SCH")))
    print()
    headers = ["period", "B old", "REG", "ENT", "SCH", "R", "B new", "state"] if lang == "en" else ["Periode", "B alt", "REG", "ENT", "SCH", "R", "B neu", "Lage"]
    ui.table(headers, rows, right=[1, 2, 3, 4, 5, 6])
    result = (
        "The resource stock ends at %s after %d period(s), and this section creates %s in resource rent. The lower B falls, the more political pressure exists for repair, limits, or higher R." %
        (ui.strip(ui.amount(b, "B")), periods, ui.strip(ui.amount(local_r, "R")))
        if lang == "en" else
        "Der Ressourcenbestand endet nach %d Periode(n) bei %s, und dieser Teil erzeugt %s Ressourcenrente. Je tiefer B fällt, desto mehr politischer Druck entsteht für Reparatur, Grenzen oder höheres R." %
        (periods, ui.strip(ui.amount(b, "B")), ui.strip(ui.amount(local_r, "R")))
    )
    possible = (
        [
            "Recovery outcome: REG exceeds ENT and SCH; B rises and R becomes small.",
            "Depletion outcome: ENT and SCH dominate; B falls, R rises, and the economy receives a clear scarcity warning.",
            "Managed outcome: higher R funds repair work, which can increase future REG and reduce long-run damage.",
        ] if lang == "en" else [
            "Erholungsausgang: REG übersteigt ENT und SCH; B steigt und R wird klein.",
            "Auslaugungsausgang: ENT und SCH dominieren; B fällt, R steigt, und die Wirtschaft erhält eine klare Knappheitswarnung.",
            "Gesteuerter Ausgang: Höheres R finanziert Reparaturarbeit, die spätere REG erhöhen und Langzeitschäden senken kann.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_damage(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["damage"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    cases = [
        ("wrong statics", "Fehlerhafte Statik", 40.0, 15.0, 90.0, 1.70, 10.0, 0.20),
        ("meeting without decision", "Meeting ohne Entscheidung", 10.0, 5.0, 12.0, 1.00, 7.0, 0.50),
        ("environmental repair", "Umweltreparatur", 30.0, 80.0, 5.0, 1.50, 5.0, 1.10),
        ("corrected map", "Korrigierte Landkarte", 22.0, 70.0, 8.0, 1.30, 8.0, 1.15),
        ("bad algorithm patched", "Schlechter Algorithmus repariert", 28.0, 74.0, 18.0, 1.60, 10.0, 1.05),
    ]
    rows: List[List[object]] = []
    debt_cases = 0
    total_positive = 0.0
    for en, de, e, op, om, gamma, k, q in cases:
        mwir = e + op - gamma * om
        aw = max(0.0, mwir) * k * q
        debt = max(0.0, -mwir) * k
        if debt:
            debt_cases += 1
        total_positive += aw
        state.damage_debt += debt
        rows.append([de if lang == "de" else en, ui.amount(e, "E"), ui.amount(op, "O+"), ui.amount(om, "O-"), ui.amount(gamma, "γ"), ui.amount(mwir, "Mwir", signed=True), ui.amount(k, "K", 1), ui.amount(q, "Q"), ui.amount(aw, "AW"), ui.amount(-debt, "AW", signed=True) if debt else ui.c("0", fg=82, bold=True)])
    ui.kv(L(lang, "formula"), "%s = %s + %s − %s·%s" % (ui.unit("Mwir"), ui.unit("E"), ui.unit("O+"), ui.unit("γ"), ui.unit("O-")))
    print()
    headers = ["case", "E", "O+", "O-", "γ", "Mwir", "K", "Q", "AW", "debt"] if lang == "en" else ["Fall", "E", "O+", "O-", "γ", "Mwir", "K", "Q", "AW", "Schuld"]
    ui.table(headers, rows, right=[1, 2, 3, 4, 5, 6, 7, 8, 9])
    result = (
        "Damage accounting credited %s but also produced %s in debt across %d damaging case(s). The model rewards repair and correction, but punishes false or harmful high-factor claims." %
        (ui.strip(ui.amount(total_positive, "AW")), ui.strip(ui.amount(state.damage_debt, "AW")), debt_cases)
        if lang == "en" else
        "Die Schadensrechnung schrieb %s gut, erzeugte aber auch %s Schuld in %d schädlichen Fall/Fällen. Das Modell belohnt Reparatur und Korrektur, bestraft aber falsche oder schädliche Hochfaktor-Ansprüche." %
        (ui.strip(ui.amount(total_positive, "AW")), ui.strip(ui.amount(state.damage_debt, "AW")), debt_cases)
    )
    possible = (
        [
            "Repair outcome: O+ dominates O-, Mwir stays positive, and AW rewards corrective work.",
            "Harm outcome: γ·O- dominates, Mwir becomes negative, and debt replaces reward.",
            "Mixed outcome: small damage lowers AW but does not erase it if useful output is still clearly larger.",
        ] if lang == "en" else [
            "Reparaturausgang: O+ dominiert O-, Mwir bleibt positiv, und AW belohnt korrigierende Arbeit.",
            "Schadensausgang: γ·O- dominiert, Mwir wird negativ, und Schuld ersetzt Belohnung.",
            "Gemischter Ausgang: Kleiner Schaden senkt AW, löscht sie aber nicht, wenn nützlicher Output klar größer bleibt.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_period_economy(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["periods"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    sectors = [
        {"en": "food", "de": "Nahrung", "k": 1.0, "demand": 520.0 * cfg.food_s, "supply": 470.0},
        {"en": "housing", "de": "Wohnen", "k": 3.0, "demand": 430.0 * cfg.housing_s, "supply": 360.0},
        {"en": "knowledge", "de": "Wissen", "k": 10.0, "demand": 260.0 * cfg.knowledge_s, "supply": 240.0},
        {"en": "communication", "de": "Kommunikation", "k": 7.0, "demand": 310.0 * cfg.communication_s, "supply": 300.0},
        {"en": "energy", "de": "Energie", "k": stacked_factor([3, 5]), "demand": 380.0 * cfg.energy_s, "supply": 340.0},
    ]
    headers = ["sector", "K", "Q", "S", "state", "AW", "P", "T"] if lang == "en" else ["Sektor", "K", "Q", "S", "Lage", "AW", "P", "T"]
    for pno in range(1, periods + 1):
        print()
        label = ("Period %d" % pno) if lang == "en" else ("Periode %d" % pno)
        ui.sub(label, bg=25, fg=231)
        rows: List[List[object]] = []
        period_aw = 0.0
        period_p = 0.0
        for s in sectors:
            scarcity = clamp(s["demand"] / max(1.0, s["supply"]), 0.55, 3.50)
            q = clamp(rng.gauss(1.02, 0.13), 0.65, 1.42)
            m = jitter(rng, 55.0 + 0.10 * s["demand"], 0.16)
            aw = m * s["k"] * q
            price = aw * scarcity * rng.uniform(0.88, 1.16)
            levy = 0.035 * price
            state.public_fund += levy
            state.taxes += levy
            state.money_supply += max(0.0, price - aw) * 0.006
            period_aw += aw
            period_p += price
            production_push = 0.10 + 0.12 * max(0.0, scarcity - 1.0)
            s["supply"] = max(10.0, s["supply"] * 0.88 + m * production_push + rng.uniform(-8, 12))
            rows.append([s[lang], ui.amount(s["k"], "K", 1), ui.amount(q, "Q"), ui.amount(scarcity, "S"), ui.heat(scarcity, lang=lang), ui.amount(aw, "AW"), ui.amount(price, "P"), ui.amount(levy, "T")])
        emergency = max(0.0, (cfg.public_pressure - 1.0) * 125.0 + (period_p / 8200.0) * 35.0)
        if emergency > state.public_fund:
            created = emergency - state.public_fund
            state.money_supply += created
            state.public_created += created
            state.public_fund = 0.0
        else:
            state.public_fund -= emergency
        state.economy_total_aw += period_aw
        print("  " + ui.c("ledger" if lang == "en" else "Register", fg=229, bold=True) + "  " + ui.unit("GF") + "=" + ui.amount(state.public_fund, "GF") + "  " + ui.unit("GM") + "=" + ui.amount(state.money_supply, "GM"))
        ui.table(headers, rows, right=[1, 2, 3, 5, 6, 7])
        if emergency > 0:
            ui.kv("stabilisation" if lang == "en" else "Stabilisierung", ui.amount(emergency, "AW"))
    result = (
        "Across %d period(s), sectors generated %s. The public fund ends at %s and the circulating money supply is %s. This shows whether the economy is producing enough real work to support its public stabilisation." %
        (periods, ui.strip(ui.amount(state.economy_total_aw, "AW")), ui.strip(ui.amount(state.public_fund, "GF")), ui.strip(ui.amount(state.money_supply, "GM")))
        if lang == "en" else
        "Über %d Periode(n) erzeugten die Sektoren %s. Der Gemeinfonds endet bei %s und die umlaufende Geldmenge liegt bei %s. Das zeigt, ob die Wirtschaft genug reale Arbeit erzeugt, um ihre öffentliche Stabilisierung zu tragen." %
        (periods, ui.strip(ui.amount(state.economy_total_aw, "AW")), ui.strip(ui.amount(state.public_fund, "GF")), ui.strip(ui.amount(state.money_supply, "GM")))
    )
    possible = (
        [
            "Crisis spiral: S remains high, P rises, public stabilisation drains GF, and GM must expand.",
            "Balanced recovery: sector supply catches up, S cools down, T becomes enough to refill GF.",
            "Innovation boom: knowledge or communication with strong K raises AW faster than scarcity raises P.",
        ] if lang == "en" else [
            "Krisenspirale: S bleibt hoch, P steigt, Stabilisierung leert GF, und GM muss wachsen.",
            "Ausgeglichene Erholung: Sektorangebot holt auf, S kühlt ab, T reicht wieder zum Auffüllen von GF.",
            "Innovationsboom: Wissen oder Kommunikation mit starkem K hebt AW schneller, als Knappheit P erhöht.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_verification(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["verification"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    claims = [
        ("V1", "correct algorithm", "korrekter Algorithmus", 60.0, 10.0, 10.0, 1.20),
        ("V2", "meeting without recipient effect", "Meeting ohne Empfängerwirkung", 35.0, 7.0, 1.0, 0.00),
        ("V3", "artificial emergency", "künstlich erzeugter Notfall", 42.0, 4.0, 1.0, 0.70),
        ("V4", "clean supply-chain map", "sauber kartierte Lieferkette", 55.0, 8.0, 8.0, 1.12),
        ("V5", "false proof", "falscher Beweis", 50.0, 10.0, 1.0, 0.00),
        ("V6", "real bottleneck diagnosis", "echte Engpassdiagnose", 45.0, 5.0, 5.0, 1.18),
        ("V7", "clear crisis briefing", "klare Krisenbesprechung", 40.0, 7.0, 7.0, 1.10),
    ]
    rows: List[List[object]] = []
    total_aw = 0.0
    for ident, en, de, m, claim_k, checked_k, q in claims:
        aw = m * checked_k * q
        total_aw += aw
        if checked_k < claim_k or q <= 0.0:
            state.verification_reduced += 1
            status = ui.c(" %s " % (L(lang, "reduced") if q > 0 else L(lang, "rejected")), fg=16 if q > 0 else 231, bg=208 if q > 0 else 196, bold=True)
        else:
            state.verification_accepted += 1
            status = ui.c(" %s " % L(lang, "accepted"), fg=16, bg=82, bold=True)
        rows.append([ui.c(ident, fg=250, bold=True), de if lang == "de" else en, ui.amount(m, "M"), ui.amount(claim_k, "K", 1), ui.amount(checked_k, "K", 1), ui.amount(q, "Q"), ui.amount(aw, "AW"), status])
    headers = ["ID", "case", "M", "claimed K", "checked K", "Q", "AW", "status"] if lang == "en" else ["ID", "Prüffall", "M", "behauptet K", "geprüft K", "Q", "AW", "Status"]
    ui.table(headers, rows, right=[2, 3, 4, 5, 6])
    result = (
        "Verification accepted %d case(s), reduced or rejected %d case(s), and credited %s after checks. The expensive factors survive only when evidence survives." %
        (state.verification_accepted, state.verification_reduced, ui.strip(ui.amount(total_aw, "AW")))
        if lang == "en" else
        "Die Prüfung bestätigte %d Fall/Fälle, kürzte oder lehnte %d Fall/Fälle ab und schrieb nach Prüfung %s gut. Die teuren Faktoren überleben nur, wenn der Nachweis überlebt." %
        (state.verification_accepted, state.verification_reduced, ui.strip(ui.amount(total_aw, "AW")))
    )
    possible = (
        [
            "Honest high-factor outcome: mathematics, block mapping, or crisis communication is confirmed and paid strongly.",
            "Fraud-control outcome: a meeting or artificial emergency loses K and cannot drain AW from the system.",
            "Zero-quality outcome: false proof or harmful model receives Q=0, so the colourful claim becomes no credit.",
        ] if lang == "en" else [
            "Ehrlicher Hochfaktor-Ausgang: Mathematik, Blockkartierung oder Krisenkommunikation wird bestätigt und stark bezahlt.",
            "Betrugskontroll-Ausgang: Ein Meeting oder künstlicher Notfall verliert K und kann dem System keine AW entziehen.",
            "Nullqualitäts-Ausgang: Falscher Beweis oder schädliches Modell erhält Q=0, sodass der farbige Anspruch keine Gutschrift wird.",
        ]
    )
    end_section(ui, lang, result, possible)


def part_final(ui: UI, lang: str, state: SimState, cfg: Scenario, periods: int, rng: random.Random) -> None:
    spec = SPECS["final"]
    begin_section(ui, lang, spec)
    ui.sub(L(lang, "calculation"), bg=60, fg=231)
    block_aw = sum(b.aw for b in state.blocks)
    total_aw_like = block_aw + state.project_stack + state.economy_total_aw
    rows = [
        ("work blocks", "Arbeitsblöcke", ui.amount(block_aw, "AW"), "verified individual work" if lang == "en" else "geprüfte Einzelarbeit"),
        ("project stack", "Projektstapel", ui.amount(state.project_stack, "ST"), "house-like stacked value" if lang == "en" else "hausartiger Stapelwert"),
        ("sector work", "Sektorarbeit", ui.amount(state.economy_total_aw, "AW"), "multi-period production" if lang == "en" else "Mehrperioden-Produktion"),
        ("total work value", "Arbeitswert gesamt", ui.amount(total_aw_like, "AW"), "new work only" if lang == "en" else "nur neue Arbeit"),
        ("public fund", "Gemeinfonds", ui.amount(state.public_fund, "GF"), "remaining public account" if lang == "en" else "öffentliches Restkonto"),
        ("money supply", "Geldmenge", ui.amount(state.money_supply, "GM"), "circulating currency" if lang == "en" else "umlaufende Währung"),
        ("transaction levies", "Transaktionsabgaben", ui.amount(state.taxes, "T"), "collected from exchange" if lang == "en" else "aus Tausch gesammelt"),
        ("resource rents", "Ressourcenrenten", ui.amount(state.resource_rent, "R"), "pressure from resource use" if lang == "en" else "Druck aus Ressourcennutzung"),
        ("credit issued", "Kredit ausgegeben", ui.amount(state.credit_issued, "KR"), "temporary finance" if lang == "en" else "vorläufige Finanzierung"),
        ("credit debt", "Kreditschuld", ui.amount(state.credit_debt, "AW"), "uncovered inventory loss" if lang == "en" else "ungedeckter Lagerverlust"),
        ("damage debt", "Schadensschuld", ui.amount(state.damage_debt, "AW"), "negative work liability" if lang == "en" else "Haftung aus negativer Arbeit"),
    ]
    table_rows = [[de if lang == "de" else en, value, meaning] for en, de, value, meaning in rows]
    headers = ["balance", "value", "meaning"] if lang == "en" else ["Größe", "Wert", "Bedeutung"]
    ui.table(headers, table_rows, right=[1])

    # Interpret the overall state.
    gm_ratio = state.money_supply / 20000.0
    gf_state = "healthy" if state.public_fund > 1500 else "thin" if state.public_fund > 0 else "empty"
    resource_state = "healthy" if state.final_resource_stock > 900 else "stressed" if state.final_resource_stock > 700 else "depleted"
    if lang == "de":
        gf_state = {"healthy": "gesund", "thin": "dünn", "empty": "leer"}[gf_state]
        resource_state = {"healthy": "gesund", "stressed": "belastet", "depleted": "ausgelaugt"}[resource_state]
    result = (
        "Final reading: total new work-like value is %s. The public fund is %s, resource stock is %s, and GM is %.2f times its opening level. The simulation is strongest when AW grows through verified work while GF, KR and R remain under control." %
        (ui.strip(ui.amount(total_aw_like, "AW")), gf_state, resource_state, gm_ratio)
        if lang == "en" else
        "Schlusslesart: Der gesamte neue arbeitsartige Wert beträgt %s. Der Gemeinfonds ist %s, der Ressourcenbestand ist %s, und GM liegt beim %.2f-fachen des Anfangsstands. Die Simulation ist am stärksten, wenn AW durch geprüfte Arbeit wächst, während GF, KR und R unter Kontrolle bleiben." %
        (ui.strip(ui.amount(total_aw_like, "AW")), gf_state, resource_state, gm_ratio)
    )
    possible = (
        [
            "Stable economy: AW grows mainly through verified blocks, GF remains funded, KR is repaid, and R finances repair before B collapses.",
            "Inflation risk: GM rises faster than useful AW because public creation or bad credit expands circulation without matching output.",
            "Ecological bottleneck: R grows because resource stocks fall; prices and public policy must redirect work into regeneration.",
            "High-leverage boom: verified mathematics, communication and block decomposition raise productivity without repeated counting of old stacks.",
        ] if lang == "en" else [
            "Stabile Wirtschaft: AW wächst vor allem durch geprüfte Blöcke, GF bleibt finanziert, KR wird zurückgezahlt, und R finanziert Reparatur, bevor B zusammenbricht.",
            "Inflationsrisiko: GM steigt schneller als nützliche AW, weil öffentliche Erzeugung oder schlechter Kredit den Umlauf ohne passenden Output erweitern.",
            "Ökologischer Engpass: R wächst, weil Bestände fallen; Preise und Politik müssen Arbeit in Regeneration umlenken.",
            "Hochhebel-Boom: Geprüfte Mathematik, Kommunikation und Blockzerlegung erhöhen Produktivität ohne wiederholte Zählung alter Stapel.",
        ]
    )
    end_section(ui, lang, result, possible)


PART_FUNCS: Dict[str, Callable[[UI, str, SimState, Scenario, int, random.Random], None]] = {
    "factors": part_factor_scale,
    "work": part_work_blocks,
    "project": part_project_stack,
    "market": part_market,
    "fund": part_public_fund,
    "credit": part_credit,
    "resources": part_resources,
    "damage": part_damage,
    "periods": part_period_economy,
    "verification": part_verification,
    "final": part_final,
}

DEFAULT_ORDER = ["factors", "work", "project", "market", "fund", "credit", "resources", "damage", "periods", "verification", "final"]
SHORT_ORDER = ["factors", "work", "market", "final"]
PART_ALIASES = {
    "all": "all", "alle": "all", "full": "all", "voll": "all",
    "short": "short", "kurz": "short",
    "factors": "factors", "faktoren": "factors",
    "work": "work", "arbeit": "work",
    "project": "project", "projekt": "project",
    "market": "market", "markt": "market",
    "fund": "fund", "fonds": "fund",
    "credit": "credit", "kredit": "credit",
    "resources": "resources", "ressourcen": "resources",
    "damage": "damage", "schaden": "damage",
    "periods": "periods", "perioden": "periods",
    "verification": "verification", "pruefung": "verification", "prüfung": "verification",
    "final": "final", "schluss": "final",
}


def parse_parts(value: str) -> List[str]:
    value = (value or "all").strip().lower()
    if value in PART_ALIASES:
        normalized = PART_ALIASES[value]
        if normalized == "all":
            return list(DEFAULT_ORDER)
        if normalized == "short":
            return list(SHORT_ORDER)
    result: List[str] = []
    for raw in value.split(","):
        key = raw.strip().lower()
        if not key:
            continue
        if key not in PART_ALIASES or PART_ALIASES[key] in ("all", "short"):
            allowed = ", ".join(DEFAULT_ORDER)
            raise SystemExit("Unknown part '%s'. Allowed examples: all, short, %s" % (raw, allowed))
        result.append(PART_ALIASES[key])
    if len(result) > 1 and "final" not in result:
        result.append("final")
    return result


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Very colorful PyPy3 UTF-8 simulation of the GAW labour-currency economy. Default output language is English.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--lang", "--language", choices=["en", "de"], default="en",
                        help="output language; English is default")
    parser.add_argument("--scenario", "--szenario", default="normal",
                        help="normal, crisis/krise, research/forschung, housebuilding/hausbau")
    parser.add_argument("--periods", "--perioden", type=int, default=6,
                        help="number of periods in the resource and sector loops")
    parser.add_argument("--seed", type=int, default=42,
                        help="random seed for reproducible simulation values")
    parser.add_argument("--parts", "--teile", default="all",
                        help="all/alle, short/kurz or comma list: factors,work,project,market,fund,credit,resources,damage,periods,verification,final")
    parser.add_argument("--width", "--breite", type=int, default=None,
                        help="terminal width for wrapping and tables")
    parser.add_argument("--no-color", action="store_true",
                        help="disable ANSI colors while keeping UTF-8 art")
    return parser


def run(args: argparse.Namespace) -> None:
    lang = args.lang
    color_enabled = (not args.no_color) and (os.environ.get("NO_COLOR") is None)
    ui = UI(color=color_enabled, width=args.width)
    rng = random.Random(args.seed)
    cfg = scenario_config(args.scenario)
    periods = max(1, min(60, int(args.periods)))
    state = SimState(seed=args.seed, scenario=cfg.key)
    parts = parse_parts(args.parts)
    part_banner(ui, lang, state, cfg, periods)
    for part in parts:
        PART_FUNCS[part](ui, lang, state, cfg, periods, rng)
    print()
    ui.rule("█", UI.RAINBOW)
    print(ui.rainbow("  " + L(lang, "end") + "  ", UI.RAINBOW))
    ui.rule("█", UI.RAINBOW)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    try:
        run(args)
    except KeyboardInterrupt:
        print("\nInterrupted." if args.lang == "en" else "\nAbgebrochen.", file=sys.stderr)
        return 130
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
